/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MandalartRouteImport } from './routes/mandalart'
import { Route as IndexRouteImport } from './routes/index'

const MandalartRoute = MandalartRouteImport.update({
  id: '/mandalart',
  path: '/mandalart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mandalart': typeof MandalartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mandalart': typeof MandalartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mandalart': typeof MandalartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mandalart'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mandalart'
  id: '__root__' | '/' | '/mandalart'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MandalartRoute: typeof MandalartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mandalart': {
      id: '/mandalart'
      path: '/mandalart'
      fullPath: '/mandalart'
      preLoaderRoute: typeof MandalartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MandalartRoute: MandalartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
